#! /bin/sh

# file      : bootstrap
# copyright : Copyright (c) 2013-2014 Code Synthesis Tools CC
# license   : MIT; see accompanying LICENSE file

#
# Bootstrap the automake build system.
#

rm -f config.cache

if test ! -d m4; then
  mkdir m4
fi

autoreconf --install
